package org.brailleblaster.libembosser.spi;

public enum MultiSides {
	INTERPOINT, P1ONLY, P2ONLY,
	SADDLE_STITCH_SINGLE_SIDED, SADDLE_STITCH_DOUBLE_SIDED,
	Z_FOLDING_SINGLE_HORIZONTAL, Z_FOLDING_DOUBLE_HORIZONTAL,
	Z_FOLDING_SINGLE_VERTICAL, Z_FOLDING_DOUBLE_VERTICAL;
}
